version: '3'

services:
  express:
    container_name: snippets_ba
    build:
      context: ./Express
    volumes:
      - ./Express:/usr/app/Express
    ports:
      - "5000:5000"
  db:
    image: mongo
    container_name: "snippets_db"
    restart: always
    volumes:
      - dbdata:/data/db
    logging:
      driver: none
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  react:
    container_name: "snippets_fr"
    build:
      context: ./React
    volumes:
      - ./React/client:/usr/app/React/client
    ports:
      - "3000:3000"
    working_dir: /usr/app/React/client
    command: npm start
volumes:
  dbdata: